# Generated by Django 3.2.5 on 2022-05-29 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('course', models.CharField(choices=[('CS', 'Computer Science'), ('MECH', 'Mechanical Engineering'), ('CIVIL', 'Civil Engineering'), ('ELE', 'Electrical Engineering'), ('EC', 'Electronics Engineering')], max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('phone', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(10)])),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='pics/')),
            ],
        ),
    ]
