# Generated by Django 3.2.5 on 2022-05-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_studentregistration_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
